export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST'
export const CREATE_ORDER_REQUEST_SUCCESS = 'CREATE_ORDER_REQUEST_SUCCESS'
export const CREATE_ORDER_REQUEST_FAIL = 'CREATE_ORDER_REQUEST_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'